### ISSUE TITLE
The UART connector labels are wrong

### ISSUE THREAD

**Issue by nseidle** [sparkfunX/Qwiic_IMU_BNO080#1]

**Comment by ramiss** [comment]
Maybe you could be helpful and list the correct pins?

**Comment by nseidle** [comment]
I apologize. This issue is old and refers to the original board version listed [here](https://www.sparkfun.com/products/retired/14586) and has since been fixed in the [precision version](https://www.sparkfun.com/products/retired/14618) and the [current red version](https://www.sparkfun.com/products/14686).

![image](https://user-images.githubusercontent.com/117102/43176907-12f84788-8f83-11e8-83bc-3a4408b252c6.png)

The original version had the UART labels reversed but as long as you followed [this image](https://cdn.sparkfun.com//assets/parts/1/2/7/3/3/BNO080_IMU_with_Serial.jpg) it would work fine.
